baseurl: /accessibility
markdown: redcarpet
name: Accessibility Guide
sass:
    sass_dir: styles/_sass

# Build settings
exclude:
- README.md
- LICENSE.md
- CONTRIBUTING.md
- deploy
- vendor
- go

permalink: pretty

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "default"
      edit_info:
        repo: 18F/accessibility
        branch: master

# DOCter bits after this

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: index.html
  internal: true
- text: Keyboard Access
  url: keyboard/
  internal: true
- text: Images
  url: images/
  internal: true
- text: Color and Contrast
  url: color/
  internal: true
- text: Forms
  url: forms/
  internal: true
- text: Flashing
  url: flashing/
  internal: true
- text: Page Titles
  url: pagetitles/
  internal: true
- text: Multimedia
  url: multimedia/
  internal: true
- text: Time Outs
  url: timeouts/
  internal: true
- text: Web Text Properties
  url: properties/
  internal: true
- text: Tables
  url: tables/
  internal: true
- text: CSS Dependence
  url: css/
  internal: true
- text: Frames
  url: frames/
  internal: true
- text: Links and Repetitive Content
  url: links/
  internal: true
- text: Plug-ins
  url: plugins/
  internal: true
- text: Alternative Versions
  url: alternativeversions/
  internal: true


repos:
- name: Accessibility
  description: Main repository
  url: https://github.com/18F/accessibility

# Style Variables
brand_color: "#1188ff"
