version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node-browsers
    environment:
      ACCESSLINT_MASTER_BRANCH: 18f-pages
    steps:
      - checkout
      - run:
          name: Display versions
          command: |
            echo $(ruby --version)
            echo $(node --version)
            echo $(npm --version)
      - run: sudo npm install -g axe-cli@3.0.0 --unsafe-perm
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - store_artifacts:
          path: /tmp
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: test
          command: bundle exec jekyll serve --detach && axe http://localhost:4000
workflows:
  version: 2
  commit:
    jobs:
      - build
