version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node
    environment:
      ACCESSLINT_MASTER_BRANCH: 18f-pages
    steps:
      - checkout
      - run:
          name: Display versions
          command: |
            echo $(ruby --version)
            echo $(node --version)
            echo $(npm --version)
      - run: sudo npm install -g axe-cli --unsafe-perm
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec jekyll build
      - store_artifacts:
          path: /tmp
      - run:
          name: test
          command: bundle exec jekyll serve --detach && axe http://localhost:4000
workflows:
  version: 2
  commit:
    jobs:
      - build